package com.example.project7.laguage.fr;

public enum StringLangFR {

    oui("Oui"),
    Non("Non"),
    Modifier("Changer"),
    Fermer("Fermer"),
    Editheader("Modifier l'en-tête de l'examen"),
    EditResHeader("Modifier l'en-tête de réponse"),
    editerQuizSec("editer_quiz/_3_EditerSection"),
    AjoutSec("Ajouter une section"),
    CheminStyle("/com/example/project7/css/styles.css"),
    Errtext("Erreur lors de l'ouverture de la popup : "),
    SelSect("Sélectionner une section"),
    ID("ID"),
    TypSec("Type de section"),
    id("id"),
    type("type"),
    Select("Sélectionner"),
    tiret("_"),
    cnt("cnt"),
    QCU("QCU"),
    QCM("QCM"),
    QuesLibre("Question ouverte"),
    Descrpt("Description"),
    ErrimpSec("Erreur lors de l'insertion de la section importée : "),
    idsec("idSection"),
    idqcm("idQCM"),
    iddesp("idDescription"),
    ConfCancel("Confirmer l'annulation"),
    CancelModif("Êtes-vous sûr de vouloir annuler les modifications ?"),
    popupmodif("Toutes les modifications seront perdues !"),
    Home("Accueil"),
    idcontr("idControle"),
    nomdev("nomDevoir"),
    typedev("typeDevoir"),
    nombrexemplaire("nombreExemplaire"),
    randseed("randomSeed"),
    Examheader("enTêteExamen"),
    Respheader("enTêteRéponse"),
    CreationDate("dateDeCréation"),
    Failedinsertdata("Échec de l'insertion des données de contrôle."),
    Errdata("Erreur lors de l'insertion des données dans la table de contrôle : "),
    ErrControle("Erreur lors de la vérification de la table de contrôle : "),
    question("question"),
    moveUpButton("↑"),
    modifierButton("i"),
    supprimerButton("X"),
    moveDownButton("↓"),
    ConsignesQuestions("Dans ce document, vous trouverez d'abord les questions puis ensuite les feuilles de réponses.\n" +
            "Les questions faisant apparaître le symbole :¨: peuvent avoir zéro, une ou plusieurs bonnes réponses. Les autres ont une unique bonne réponse. " +
            "Des points négatifs sont attribués pour les mauvaises réponses. La pondération des mauvaises réponses est nulle pour les premières fausses réponses, " +
            "mais ensuite la pondération (négative) des mauvaises réponses augmente avec le nombre de mauvaises réponses.\n" +
            "Un document ressource est distribué en plus de ce document. Vous devez utiliser les informations de ce document en priorité.\n"),
    Consigne2("2 feuilles détachables (4 pages) : seuls documents à rendre pour l'examen de Microprocesseur."),
    Randseedpardefaut("12345678"),
    nbrexmppardefaut("1"),
    Failedtoupdatesection("Échec de la mise à jour de la section : "),
    Errorupdatingsection("Erreur lors de la mise à jour de la section : "),
    ModifierSectionQCU("Modifier la section QCU"),
    Erreurlorsdeouverturedelapopup("Erreur lors de l'ouverture de la popup : "),
    ConfirmDeletion("Confirmer la suppression"),
    SureofDeletemssg("Êtes-vous sûr de vouloir supprimer la section : "),
    PointIntegoration("?"),
    thisactionCantBeDone("Cette action ne peut pas être annulée."),
    Nosect("Aucune section trouvée à supprimer avec idSection : "),
    Errsect("Erreur lors de la suppression de la section : "),
    QcuetQcm("QCU/QCM"),
    isQCU("isQCU"),
    OrdreSect("ordreSection"),
    Errdataloading("Erreur lors du chargement des données de section : "),
    response("réponse"),
    score("score"),
    correct("estCorrect"),
    nbrligne("nombreLigne"),
    taillelign("tailleLigne"),
    RAPPEL("rappel"),
    scoretotal("scoreTotal"),
    nbrscore("nombreScore"),
    text("texte"),
    imagpath("imagePath"),
    legendtext("legendText"),
    imgwidth("imageWidth"),
    succes("Succès"),
    succesContr("Le contrôle a été ajouté avec succès."),
    Err("Erreur"),
    FailedUpdtaeContr("Échec de la mise à jour du contrôle."),
    Errupdate("Erreur lors de la mise à jour du contrôle : "),
    ErrUpdateProjet("Il y a eu une erreur lors de la mise à jour du projet !"),
    ErrControl("Erreur lors de la mise à jour du contrôle : "),
    diez("#"),
    Deuxpoints(" : "),
    home("Accueil"),
    tex(".tex"),
    pathAMC("/com/example/project7/latex/automultiplechoice.sty"),
    RessourcenotFound("Ressource automultiplechoice.sty non trouvée."),
    AMCfihcierSTY("automultiplechoice.sty"),
    pdflatex("pdflatex"),
    pdfSucces("PDF généré avec succès."),
    pdf(".pdf"),
    PDFNOTFOUND("Fichier PDF non trouvé : "),
    DESKTOPnotsupported("Le bureau n'est pas supporté sur cette plateforme."),
    pdfFAIL("Échec de la génération du PDF avec le code de sortie : "),
    imgfiles("Fichiers d'image"),
    png("*.png"),
    jpg("*.jpg"),
    jpeg("*.jpeg"),
    point("."),
    SectionExists("La section existe"),
    SectionAlreadyExist("La section existe déjà"),
    SectionId("Section avec l'identifiant "),
    Sectionexistedeja(" existe déjà, voulez-vous l'écraser ?"),
    cancel("Annuler"),
    x("X"),
    ErrcheckExist("Erreur lors de la vérification de l'existence de la section : "),
    Errinsert("Erreur lors de l'insertion des données de la section : "),
    FailedInsertion("Échec de l'insertion de la description."),
    ErrInsert("Erreur lors de l'insertion : "),
    ErrloadingQCU("Erreur lors du chargement des données QCU : "),
    Textdanger("text-field-danger"),
    CorrAnswer("Bonne réponse"),
    WrongAnswer("Mauvaise réponse"),
    Supprimer("Supprimer"),
    ErrdltSec("Erreur lors de la suppression de la section : "),
    failInsrtQcudata("Échec de l'insertion des données QCU."),
    ErrInsrtQcudata("Erreur lors de l'insertion des données QCU : "),
    ErrWrongAnsw("Erreur lors de l'insertion des réponses incorrectes : "),
    EntrBareme("Entrez le barème"),
    save("Enregistrer"),
    close("Fermer"),
    ChngAnswAndBareme("Modifier la réponse et le barème :"),
    ChangAnswr("Modifier la réponse"),
    EdtQues("Modifier la question"),
    EdtCorrAnswr("Modifier la réponse correcte"),
    QuesNmr("Question N°"),
    SecID("sectionID"),
    EdtDescrpt("_7_EditerDescription"),
    section("Section#"),
    Pane("editer_quiz/"),
    content("Le contenu pour "),
    CantCharge(" n'a pas pu être chargé."),
    Errchargement("Erreur lors du chargement de "),
    fxml(".fxml"),
    EditerQCM("_4_EditerQCM"),
    EditerQCU("_5_EditerQCU"),
    EditerQuestion("_6_EditerQuestionLibre"),
    EditerDesp("_7_EditerDescription"),
    ErrOrderSec("Erreur lors de la mise à jour de l'ordre de la section : "),
    MssgContollErr("Le contrôleur actuel n'est pas une instance de EditerQCU."),
    OUCHY("OUCHY !!"),
    EdtQuizetPrjt("editer_quiz/_2_EditerProjet"),
    SelectPrjt("Vous devez d'abord sélectionner un projet"),
    SelectPrjtOPen("Vous devez d'abord sélectionner un projet pour l'ouvrir "),
    nomProjet("nomProjet"),
    PathPrjt("localisationProjet"),
    typePrjt("typeProjet"),
    date("date"),
    idPrjt("idProjet"),
    SureDeletePrjt("Êtes-vous sûr de vouloir supprimer le projet : "),
    ThisActUNDONE("Cette action ne peut pas être annulée, mais les fichiers dans "),
    willRemain(" resteront"),
    NoprjtFOUND("Aucun projet trouvé à supprimer avec l'identifiant : "),
    ErrDELETE("Erreur lors de la suppression du projet : "),
    ErrCreatingFolder("Une erreur s'est produite lors de la création du dossier du projet !"),
    ErrCreatingPrjt("Une erreur s'est produite lors de la création du projet !"),
    ErrVerfNamePrj("Erreur de base de données : Impossible de vérifier le nom du projet !"),
    NameAlreadyExists("Le nom de votre projet existe déjà !"),
    EnterNamePrjt("Vous devez entrer le nom de votre projet !"),
    SpecCHAR("[a-zA-Z0-9 _-]+"),
    NoSpecCHAR("Le nom du projet ne doit pas contenir de caractères spéciaux !"),
    StartWithLETTER("Le nom de votre projet doit commencer par une lettre !"),
    ChoosePrjtPATH("Vous devez choisir un emplacement pour le projet !"),
    PathNOTFound("L'emplacement sélectionné n'est pas valide ou n'existe pas."),
    userHome("user.home"),
    Controle("Controle{"),
    ;

    private final String name ;

    StringLangFR(String name) {
        this.name = name;
    }

    public String getValue(){
        return name;
    }
}
